# Read the Docs configuration file for Sphinx projects
version: 2

# Build environment settings
build:
  os: ubuntu-22.04  # Operating system to use
  tools:
    python: "3.12"  # Specify the Python version

# Path to Sphinx's configuration file (conf.py)
sphinx:
  configuration: docs/conf.py  # Adjust the path based on your project structure

# Python dependencies required to build the docs
python:
  install:
    - requirements: docs/requirements.txt
